"""
Run once against a fresh database: python -m scripts.seed_tags
Seeds a starter tag taxonomy. Extend this list as needed — the schema
supports arbitrary tags of type 'nationality', 'region', or 'hobby'.
Region labels come from app.services.regions (region_country.json).
"""

import asyncio

from sqlalchemy import select

from app.db.session import AsyncSessionLocal
from app.models.tag import Tag
from app.services.regions import ALL_REGIONS

NATIONALITIES = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua & Deps",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Rep",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo {Democratic Rep}",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland {Republic}",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea North",
    "Korea South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar, {Burma}",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "St Kitts & Nevis",
    "St Lucia",
    "Saint Vincent & the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome & Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad & Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]

HOBBIES = [
    "Basketball",
    "Football",
    "Soccer",
    "Rugby",
    "Water Polo",
    "Handball",
    "Baseball",
    "Cricket",
    "Softball",
    "Kickball",
    "Tennis",
    "Volleyball",
    "Table Tennis",
    "Squash",
    "Golf",
    "Bowling",
    "Billiards",
    "Pool",
    "Curling",
    "Skating",
    "Gym",
    "Badminton",
    "Dance",
    "Chess",
    "Cycling",
    "Reading",
]


async def seed():
    async with AsyncSessionLocal() as db:
        for label in NATIONALITIES:
            exists = await db.execute(select(Tag.id).where(Tag.tag_type == "nationality", Tag.label == label))
            if exists.scalar_one_or_none() is None:
                db.add(Tag(tag_type="nationality", label=label))
        for label in ALL_REGIONS:
            exists = await db.execute(select(Tag.id).where(Tag.tag_type == "region", Tag.label == label))
            if exists.scalar_one_or_none() is None:
                db.add(Tag(tag_type="region", label=label))
        for label in HOBBIES:
            exists = await db.execute(select(Tag.id).where(Tag.tag_type == "hobby", Tag.label == label))
            if exists.scalar_one_or_none() is None:
                db.add(Tag(tag_type="hobby", label=label))
        await db.commit()
    print(
        f"Seeded {len(NATIONALITIES)} nationality tags, {len(ALL_REGIONS)} region tags, "
        f"and {len(HOBBIES)} hobby tags."
    )


if __name__ == "__main__":
    asyncio.run(seed())
